trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/customers/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "customers"
urlpatterns = [
    path('', views.index, name="index"),
    path('sign_up/', views.sign_up, name="sign_up"),
    path('change/', views.change, name='change'),
    path('one_time_pickup/', views.one_time_pickup, name='one_time_pickup'),
    path('account_info/', views.account_info, name='account_info'),
    path('suspend_account/', views.suspend_account, name="suspend_account"),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),
    path('filter_pickups/', views.filter_pickups, name='filter_pickups'),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <title>{% block title %}{% endblock %}</title>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static 'css/static.styles.css' %}" rel="stylesheet">
</head>
<body style="background-image: url('{% static "yoneken-1Iugn-FSIZw-unsplash.jpeg" %}'">
{% if user.is_authenticated %}
  {% for group in user.groups.all%}
    {% if group.name == "Customers" %}
    <nav class="navbar navbar-expand-sm bg-light justify-content-center">
       <ul class="navbar-nav" >
           <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'customers:index' %}">Home</a>
          </li>
          <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'customers:change' %}">Change Pickup Day</a>
          </li>
           <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'customers:one_time_pickup' %}">Schedule One Time Pickup</a>
          </li>
           <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'customers:account_info' %}">Account Information</a>
          </li>
           <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'customers:suspend_account' %}">Suspend Services</a>
          </li>
       </ul>
    </nav><br>
    {% elif group.name == "Employees" %}
     <nav class="navbar navbar-expand-sm bg-light justify-content-center">
       <ul class="navbar-nav">
           <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'employees:index' %}">Home</a>
          </li>
           <li class="nav-item">
              <a class="nav-link text-success h5" href="{% url 'employees:filter_pickups' %}">Filter Daily Pickups</a>
          </li>
       </ul>
    </nav><br>
    {% endif %}
  {% endfor %}
    <button type="submit" class="btn btn-success"> <a class="text-white" href="{% url 'logout' %}"> Log Out</a></button>
{% endif %}
  <main>
    <h1>{% block header %} {% endblock %}</h1>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>
{# This is the parent template that should be extended by any other view you create #}
{# Todo: Add navbar links, link to stylesheets, style layout #}

trash_collector/templates/home.html
{% extends 'base.html' %}

{% block title %} Home Portal {% endblock %}

{% block header %} Home Portal {% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hello {{ user.username }}. You don't have a group assigned. Please contact administrator or attempt to register again.
  <p><a href="{% url 'logout' %}">Log Out</a></p>
{% else %}
  <h4>You are not logged in. Please log in or create an account.</h4>
  <button type="submit" class="btn btn-success"> <a class="text-white" href="{% url 'login' %}" > Log In</a></button> |

  <button type="submit" class="btn btn-success"> <a class="text-white" href="{% url 'accounts:register' %}" > Sign Up</a></button>
{% endif %}
{% endblock %}

{# This is the home page that allows a logged out user to register or log in #}