trash_collector/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
]

trash_collector/employees/urls.py
from django.urls import path

from . import views

# TODO: Determine what distinct pages are required for the customer user stories, add a path for each in urlpatterns

app_name = "employees"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('confirm_pickup/<int:customer_id>/', views.confirm_pickup, name='confirm_pickup'),
    path('filter_pickups/', views.filter_pickups, name='filter_pickups'),
]

trash_collector/trash_collector/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    # First adding our custom routes from our accounts app's urls.py (for our custom registration)
    path('accounts/', include('accounts.urls')),
    # Then adding django's built in routes (login and logout). Notice there is no login function in accounts/views.py
    path('accounts/', include('django.contrib.auth.urls')),
    # Adding all urls from customer app
    path('customers/', include('customers.urls')),
    # Adding all urls from employees app
    path('employees/', include('employees.urls')),
    # 'home' redirects a user to the appropriate index based on their auth group. Investigate views.py for more info
    path('', views.group_redirect, name='home')
]

trash_collector/employees/models.py
from django.db import models


# Create your models here.


class Employees(models.Model):
    name = models.CharField(max_length=50)
    zip_code = models.CharField(max_length=10, blank=True, null=True)
    user = models.ForeignKey('accounts.User', blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

trash_collector/employees/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.apps import apps
from .models import Employees
from datetime import date
from django.urls import reverse


# Create your views here.

# TODO: Create a function for each path created in employees/urls.py. Each will need a template as well.

def index(request):
    user = request.user

    try:
        logged_in_employee = Employees.objects.get(user=user)
        context = {
            'logged_in_employee': logged_in_employee
        }
    except:
        return HttpResponseRedirect(reverse('employees:create'))

    employee = Employees.objects.get(user_id=user.id)
    Customer = apps.get_model('customers.Customer')
    customers = Customer.objects.all()
    customers_today = []
    today = date.today()
    for customer in customers:
        if customer.zipcode == employee.zip_code and customer.suspension == False and\
                customer.pickup_day == today.strftime('%A') or customer.one_time_pickup == today:
            customers_today.append(customer)
            context = {
                'customers': customers_today
            }
    return render(request, 'employees/index.html', context)


def create(request):
    if request.method == 'POST':
        user = request.user
        name = request.POST.get('name')
        zip_code = request.POST.get('zip_code')
        new_employee = Employees(name=name, zip_code=zip_code, user=user)
        new_employee.save()
        return HttpResponseRedirect(reverse('employees:index'))
    else:
        return render(request, 'employees/create.html')


def confirm_pickup(request, customer_id):
    Customer = apps.get_model('customers.Customer')
    customer = Customer.objects.get(pk=customer_id)
    customer.user_account_balance += 5
    customer.save()
    context = {
        'customer': customer
    }
    return render(request, 'employees/confirm.html', context)


def filter_pickups(request):
    customers = apps.get_model('customers.Customer')
    employee = Employees.objects.get(user=request.user)
    employee_customers = customers.objects.filter(zipcode=employee.zip_code)
    if request.method == 'POST':
        filtered_customers = customers.objects.filter(zipcode=employee.zip_code).filter(pickup_day=request.POST.get('pickup_day'))
        context = {
            'customers': filtered_customers,
            'employee': employee
        }
        return render(request, 'employees/filter_pickups.html', context)
    else:
        context = {
            'customers': employee_customers
        }
        return render(request, 'employees/filter_pickups.html', context)

trash_collector/employees/templates/employees/confirm.html
{% extends 'base.html' %}

{% block title %} Active Accounts {% endblock %}

{% block header %}Active Accounts {% endblock %}

{% block content %}
  {% if user.is_authenticated %}
    <br><h1><u>Hello {{ user.username }}!</u></h1><br>
<h3>You have confirmed the pick up for {{customer.name}} at {{customer.address}}</h3><br><br>
<h3><span style="text-decoration:underline">{{customer.name}}</span> account balance has increased to<span style="text-decoration:underline"> {{customer.user_account_balance}}</span></h3>

  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/create.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Information {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
<h1>Hello {{ user.username }}!</h1>
   <br><h3><form action="{% url 'employees:create' %}" method="post">
    {% csrf_token %}
        <label>Name:</label><input type="text" name="name" id="name"><br>
        <label>User:</label><input type="text" name="user" id="user"><br>
        <label>Zip Code:</label><input type="text" name="zip_code" id="zip_code"><br>
        <input class="btn btn-success" type="submit" value="Submit" />
    </form></h3>
          {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}

trash_collector/employees/templates/employees/filter_pickups.html
{% extends 'base.html' %}
{# This top line allows this template to utilizing the styling and layout from the base. All your templates should do the same. #}

{% block title %} Filter Customers {% endblock %}

{% block header %} Filter Customers {% endblock %}

{% block content %}
<br><h1><u>Hello {{ user.username }}</u></h1><br>
<div class="container">
    <div class="jumbotron">
<h5><form action="{% url 'employees:filter_pickups' %}" method="post">
    {% csrf_token %}
    <label><h2>Pickup Day:</h2></label>
    <select name="pickup_day">
        <option value="Monday">Monday</option>
        <option value="Tuesday">Tuesday</option>
        <option value="Wednesday">Wednesday</option>
        <option value="Thursday">Thursday</option>
        <option value="Friday">Friday</option>
        <option value="Saturday">Saturday</option>
    </select><br>

    <input class="btn btn-success float-right" type="submit" value="Submit">
</form></h5>
</div>
    <div class="jumbotron">

<!--<h2>{{customer.name}} {{customer.address}} {{customer.pickup_day}}</h2><br/>-->
    {% for customer in customers %}
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
      <th scope="col">Pick Up Day</th>

    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row">{{customer.id}}</th>
      <td>{{customer.name}}</td>
      <td>{{customer.address}}</td>
      <td>{{customer.pickup_day}}</td>
    </tr>
    </tbody>
</table>
        {% endfor %}
</div>

    </div>
{% endblock %}

trash_collector/employees/templates/employees/index.html
{% extends 'base.html' %}

{% block title %}{% block header %} Employee Home {% endblock %}{% endblock %}

{% block content %}
  {% if user.is_authenticated %}
<br><h1><u>Hello {{ user.username }}</u></h1><br>
    <h3>Below are the customers in your route today!<br>
    Please make sure to confirm and charge all pickups!</h3><br><br>
<div class="container">
<div class="jumbotron">
{% for customer in customers %}

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Name</th>
      <th scope="col">Address</th>
        <th scope="col">Confirmation</th>

    </tr>
  </thead>

  <tbody>
    <tr>
      <th scope="row">{{customer.id}}</th>
      <td>{{customer.name}}</td>
      <td>{{customer.address}}</td>
      <td><button type="submit" class="btn btn-success"> <a class="text-white" href= "{% url 'employees:confirm_pickup' customer.id %}" > Confirm Pickup</a></button></td>
    </tr>
    </tbody>
</table>


<!--<ul>-->
<!--    <li><h3>Name: {{customer.name}}<br></h3>-->
<!--        <h3>Address: {{customer.address}} <br></h3>-->
<!--        <button type="submit" class="btn btn-success"> <a class="text-white" href= "{% url 'employees:confirm_pickup' customer.id %}" > Confirm Pickup</a></button>-->
<!--    </li>-->
<!--  </ul>-->
{% endfor %}
  {% else %}
    <p>You are at the employee index, but you are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    <a href="{% url 'accounts:register' %}">Sign Up</a>
  {% endif %}
{% endblock %}